### ISSUE TITLE
No deployment specific parameters in group_vars/all.yml

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ansible#1]
user/certbot_admin_email will be deployment specific vars. They should be extracted from group_vars/all.yml

**Comment by hbruch** [comment]
The same applies for docker-compose.yml: specific settings like router/images should be extracted

**Comment by leonardehrenfried** [comment]
> user/certbot_admin_email will be deployment specific vars. They should be extracted from group_vars/all.yml

Ok, this has been fixed in https://github.com/mfdz/digitransit-ansible/commit/ec3d93e332d2916b34a8e775ffb9f140ecb07c87

**Comment by leonardehrenfried** [comment]
> The same applies for docker-compose.yml: specific settings like router/images should be extracted

So all the image names should move into variables?

**Comment by leonardehrenfried** [comment]
I've extracted a lot of variables including the docker image names.
