### ISSUE TITLE
Make osm.pbf download-url configurable

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ansible#14]
For different setups (or to use preprocessed osm.pbf), the [pbf url](https://github.com/mfdz/digitransit-ansible/blob/00cad29caa1d5b31d659be0f16677d8d95714792/roles/tileserver/templates/build-mbtiles#L7) should be configurable

**Comment by leonardehrenfried** [comment]
That's a good point and I will definitely do it.

At the moment im in the middle of trying to get all the pieces to work together but I will eventually get around separating the tilemaker from the tileserver role.

**Comment by leonardehrenfried** [comment]
You can now set the variable `tilemaker_pbf_download_url`.

https://github.com/mfdz/digitransit-ansible/blob/master/roles/tilemaker/defaults/main.yml#L2
