### ISSUE TITLE
Make make vagrant work

### ISSUE THREAD

**Issue by frankgerhardt** [mfdz/digitransit-ansible#6]
I got this VM with 512 MB RAM
![image](https://user-images.githubusercontent.com/550621/74780395-ccf35c00-529f-11ea-98c3-140545eba5a0.png)
and not the more appropriate setup for libvirt as in the Vagrantfile
![image](https://user-images.githubusercontent.com/550621/74780438-e4cae000-529f-11ea-8b75-2634f380f014.png)

In fact I'd prefer using libvirt instead of VirtualBox but I could not find out how.

**Comment by frankgerhardt** [comment]
I got `libvirt` working. Next Ansible. The roles were missing, ok installed them. Then it fails and I don't know where.
![Screenshot_2020-02-19_00-18-49](https://user-images.githubusercontent.com/550621/74786627-75f48380-52ad-11ea-8c17-04dd44312c96.png)

**Comment by frankgerhardt** [comment]
I'm checking what `sudo` is needed for.
![image](https://user-images.githubusercontent.com/550621/74786943-37ab9400-52ae-11ea-9e99-d900dbde6d80.png)
For showing the logs, it's not worth to switch off security completely with passwordless-sudo. And it is not even needed:
![image](https://user-images.githubusercontent.com/550621/74787006-5f9af780-52ae-11ea-9515-34212bb6a2e4.png)
The group `systemd-journal` should be fine.

But why at all this config? This is a host config and who cares about the host anyway? We need to see logs on the target and not on the host.

**Comment by frankgerhardt** [comment]
Now with `make vagrant` really, as written in the Readme. Fails with the same error as above.
![Screenshot_2020-02-19_00-44-23](https://user-images.githubusercontent.com/550621/74788077-21eb9e00-52b1-11ea-8c68-65f9b565bbc8.png)

**Comment by leonardehrenfried** [comment]
You're right. Docker really must be installed _before_ the adding yourself to the `docker` group.

I will take care of it.

**Comment by leonardehrenfried** [comment]
> The Readme says "In order to execute the ansible playbook you need a user on the target host and `sudo`" Then why doesn't the playbook at first set up the user properly? Shall I do that manually? Ah, I see, it tries, but in the end there is an error **"Group docker does not exist"**.
> 
> I'm checking what `sudo` is needed for.
> ![image](https://user-images.githubusercontent.com/550621/74786943-37ab9400-52ae-11ea-9e99-d900dbde6d80.png)
> For showing the logs, it's not worth to switch off security completely with passwordless-sudo. And it is not even needed:
> ![image](https://user-images.githubusercontent.com/550621/74787006-5f9af780-52ae-11ea-9515-34212bb6a2e4.png)
> The group `systemd-journal` should be fine.

If you find a way to execute the playbook without passwordless sudo, I'd love it but I haven't got it to work. 

Vagrant boxes, however, have passwordless sudo by default. How do you intend to set a password?

**Comment by leonardehrenfried** [comment]
@frankgerhardt Please check out https://github.com/mfdz/digitransit-ansible/commit/fb1bb90f7451d0c44085813d7ac9dd0e18a48f8c

There i've changed the order of the base and docker roles. Now this part should install.

However, you still won't be able to generate the letsencrypt certificate for the vagrant box so the next step will fail.

**Comment by frankgerhardt** [comment]
For local dev the letsencrypt won't work anyway because my laptop has not public address. 
Can you `make` a setup for local dev where the letsencrypt part is skipped?
Or, we use ngrok.io a lot, where I expose my laptop that way?

**Comment by leonardehrenfried** [comment]
I can try to generate a self-signed certificate but for the time being, I suggest that you create a second playbook which doesn't contain the `letsencrypt` and digitransit roles. For this you need to copy the file `digitransit.yml` and run that.

After we have this other playbook running, I suggest that we combine the two.

Until then, I think I might have the self signed cert ready.

**Comment by leonardehrenfried** [comment]
It isn't really resolved but but I'm going to close this issue anyway since it doesn't look like we need it anymore.

If you disagree, please reopen it, @frankgerhardt .
